### ISSUE TITLE
Check if gem name is allowed

### ISSUE THREAD

**Issue by xeraa** [mrkamel/search_flip#1]
Assuming you didn't receive my email, since the naming issue is still on the todo list and you're actively working on the project — here's my reply:

> Hi Benjamin,
> 
> First of all sorry for the slow response. It’s holiday season and it took some time until your email was forwarded to the right people.
> 
> The authoritative source for this discussion is https://www.elastic.co/legal/trademarks.
> Our main goal is to avoid any confusion what is supported by us and what is not.
> Thus we would kindly ask you to change the name. But please let us know the new name, since we always try to keep track of what is going on in the ecosystem.
> 
> And we’d love to send you some swag for your efforts around Elasticsearch. Please send me your shipping address, so we can make it happen.
> 
> Out of interest: What’s the difference of your client / why did you not use the one built by my colleague Karel: https://github.com/elastic/elasticsearch-ruby
> Couldn’t find that in the readme — might be interesting to add :)
> 
> Schöne Grüße aus Wien,
> Philipp
> 
> PS: If you want to talk about your client at a meetup, let me know. We’re always looking for interesting talks.

**Comment by mrkamel** [comment]
hey, many thanks for your detailed response and feedback!
I actually received the mail, sry, i must have sorted it out erroneously.

ok, so i will rename it, no problem and i'll add the respective points to the readme, thx!
regarding meetup, ... would be nice, maybe after releasing it.

Beste Grüße aus Hamburg
  Benjamin

**Comment by mrkamel** [comment]
I finally managed to rename the project

**Comment by mrkamel** [comment]
FYI today i officially released it: https://rubygems.org/gems/search_flip

**Comment by xeraa** [comment]
Nice! Let me know if you want to do a talk about it at a meetup and I can introduce you to the right local organizers :)
