### ISSUE TITLE
Index with document id

### ISSUE THREAD

**Issue by erictuvesson** [mrkamel/search_flip#10]
Hey, I would like to index a document with id, is that possible?

**Comment by mrkamel** [comment]
sure. did you check out the readme...?

**Comment by erictuvesson** [comment]
I can't find anything of in the README unless I am missing something?

**Comment by mrkamel** [comment]
```ruby
class CommentIndex
  include SearchFlip::Index

  # ...

  def self.serialize(comment)
    {
      id: comment.id,
      # ...
    }
  end
end

CommentIndex.import Comment.find(3)
```

if that's not what you search for, please be more concrete and/or provide pseudocode about what you want to do.

**Comment by erictuvesson** [comment]
I am thinking more about `PUT /<index>/_doc/<_id>` and `PUT /<index>/_create/<_id>` that can be found [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html). It would be nice to have support for `op_type` too.

This is also a good blog post about it.
https://www.elastic.co/blog/efficient-duplicate-prevention-for-event-based-data-in-elasticsearch

**Comment by erictuvesson** [comment]
Hey again, have you had time to look at it?

**Comment by mrkamel** [comment]
you can use everything supported by the bulk api, 

```ruby
CommentIndex.import Comment.first, {}, op_type: 'create'
```

or directly

```ruby
CommentIndex.create Comment.first
```

**Comment by mrkamel** [comment]
README extended
